# Generated by Django 5.0.4 on 2024-04-07 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_profile_alter_like_user_id_alter_post_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='Profile',
        ),
    ]
