# Generated by Django 5.0.4 on 2024-04-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_author_remove_question_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
