# Generated by Django 5.0.4 on 2024-04-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_answers_answer_rename_posts_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
