# Generated by Django 5.0.4 on 2024-04-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_questions_alter_answer_related_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
