# Generated by Django 5.0.4 on 2024-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.CharField(choices=[('checked', 'checked'), ('', 'not')]),
        ),
    ]
